// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pkg/cni/proto/cni.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AddNetworkRequest contains the information needed to assign networking to a VM.
type AddNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pod namespace
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Pod name
	PodName string `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// Container/VM name within the pod
	ContainerName string `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// Internal IP of the VM (e.g., 192.168.64.x from Virtualization.framework)
	VmInternalIp  string `protobuf:"bytes,4,opt,name=vm_internal_ip,json=vmInternalIp,proto3" json:"vm_internal_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddNetworkRequest) Reset() {
	*x = AddNetworkRequest{}
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkRequest) ProtoMessage() {}

func (x *AddNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkRequest.ProtoReflect.Descriptor instead.
func (*AddNetworkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cni_proto_cni_proto_rawDescGZIP(), []int{0}
}

func (x *AddNetworkRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *AddNetworkRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *AddNetworkRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *AddNetworkRequest) GetVmInternalIp() string {
	if x != nil {
		return x.VmInternalIp
	}
	return ""
}

// AddNetworkResponse contains the assigned VPC networking information.
type AddNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VPC secondary IP assigned to this VM (e.g., 10.0.x.x)
	VpcIp string `protobuf:"bytes,1,opt,name=vpc_ip,json=vpcIp,proto3" json:"vpc_ip,omitempty"`
	// Subnet mask (e.g., "255.255.252.0" or "/22")
	SubnetMask string `protobuf:"bytes,2,opt,name=subnet_mask,json=subnetMask,proto3" json:"subnet_mask,omitempty"`
	// Gateway IP for the VPC subnet
	Gateway string `protobuf:"bytes,3,opt,name=gateway,proto3" json:"gateway,omitempty"`
	// Whether routing and NAT were successfully configured
	RoutingConfigured bool `protobuf:"varint,4,opt,name=routing_configured,json=routingConfigured,proto3" json:"routing_configured,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AddNetworkResponse) Reset() {
	*x = AddNetworkResponse{}
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNetworkResponse) ProtoMessage() {}

func (x *AddNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNetworkResponse.ProtoReflect.Descriptor instead.
func (*AddNetworkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cni_proto_cni_proto_rawDescGZIP(), []int{1}
}

func (x *AddNetworkResponse) GetVpcIp() string {
	if x != nil {
		return x.VpcIp
	}
	return ""
}

func (x *AddNetworkResponse) GetSubnetMask() string {
	if x != nil {
		return x.SubnetMask
	}
	return ""
}

func (x *AddNetworkResponse) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *AddNetworkResponse) GetRoutingConfigured() bool {
	if x != nil {
		return x.RoutingConfigured
	}
	return false
}

// DelNetworkRequest identifies the VM whose networking should be removed.
type DelNetworkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pod namespace
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Pod name
	PodName string `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// Container/VM name within the pod
	ContainerName string `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	// VPC IP to release (optional, will look up if not provided)
	VpcIp         string `protobuf:"bytes,4,opt,name=vpc_ip,json=vpcIp,proto3" json:"vpc_ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DelNetworkRequest) Reset() {
	*x = DelNetworkRequest{}
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelNetworkRequest) ProtoMessage() {}

func (x *DelNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelNetworkRequest.ProtoReflect.Descriptor instead.
func (*DelNetworkRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cni_proto_cni_proto_rawDescGZIP(), []int{2}
}

func (x *DelNetworkRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *DelNetworkRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *DelNetworkRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *DelNetworkRequest) GetVpcIp() string {
	if x != nil {
		return x.VpcIp
	}
	return ""
}

// DelNetworkResponse confirms the network was removed.
type DelNetworkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether the IP was successfully released
	Released bool `protobuf:"varint,1,opt,name=released,proto3" json:"released,omitempty"`
	// Whether routing was successfully removed
	RoutingRemoved bool `protobuf:"varint,2,opt,name=routing_removed,json=routingRemoved,proto3" json:"routing_removed,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DelNetworkResponse) Reset() {
	*x = DelNetworkResponse{}
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DelNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelNetworkResponse) ProtoMessage() {}

func (x *DelNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelNetworkResponse.ProtoReflect.Descriptor instead.
func (*DelNetworkResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cni_proto_cni_proto_rawDescGZIP(), []int{3}
}

func (x *DelNetworkResponse) GetReleased() bool {
	if x != nil {
		return x.Released
	}
	return false
}

func (x *DelNetworkResponse) GetRoutingRemoved() bool {
	if x != nil {
		return x.RoutingRemoved
	}
	return false
}

// GetNetworkInfoRequest identifies the VM to query.
type GetNetworkInfoRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Pod namespace
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// Pod name
	PodName string `protobuf:"bytes,2,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	// Container/VM name within the pod
	ContainerName string `protobuf:"bytes,3,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNetworkInfoRequest) Reset() {
	*x = GetNetworkInfoRequest{}
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkInfoRequest) ProtoMessage() {}

func (x *GetNetworkInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNetworkInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_cni_proto_cni_proto_rawDescGZIP(), []int{4}
}

func (x *GetNetworkInfoRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetNetworkInfoRequest) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *GetNetworkInfoRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

// GetNetworkInfoResponse contains the current network configuration.
type GetNetworkInfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// VPC IP assigned to this VM (empty if not assigned)
	VpcIp string `protobuf:"bytes,1,opt,name=vpc_ip,json=vpcIp,proto3" json:"vpc_ip,omitempty"`
	// Internal VM IP
	VmInternalIp string `protobuf:"bytes,2,opt,name=vm_internal_ip,json=vmInternalIp,proto3" json:"vm_internal_ip,omitempty"`
	// Whether routing is currently configured
	RoutingConfigured bool `protobuf:"varint,3,opt,name=routing_configured,json=routingConfigured,proto3" json:"routing_configured,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetNetworkInfoResponse) Reset() {
	*x = GetNetworkInfoResponse{}
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNetworkInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNetworkInfoResponse) ProtoMessage() {}

func (x *GetNetworkInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_cni_proto_cni_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNetworkInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNetworkInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_cni_proto_cni_proto_rawDescGZIP(), []int{5}
}

func (x *GetNetworkInfoResponse) GetVpcIp() string {
	if x != nil {
		return x.VpcIp
	}
	return ""
}

func (x *GetNetworkInfoResponse) GetVmInternalIp() string {
	if x != nil {
		return x.VmInternalIp
	}
	return ""
}

func (x *GetNetworkInfoResponse) GetRoutingConfigured() bool {
	if x != nil {
		return x.RoutingConfigured
	}
	return false
}

var File_pkg_cni_proto_cni_proto protoreflect.FileDescriptor

const file_pkg_cni_proto_cni_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/cni/proto/cni.proto\x12\x03cni\"\x99\x01\n" +
	"\x11AddNetworkRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12$\n" +
	"\x0evm_internal_ip\x18\x04 \x01(\tR\fvmInternalIp\"\x95\x01\n" +
	"\x12AddNetworkResponse\x12\x15\n" +
	"\x06vpc_ip\x18\x01 \x01(\tR\x05vpcIp\x12\x1f\n" +
	"\vsubnet_mask\x18\x02 \x01(\tR\n" +
	"subnetMask\x12\x18\n" +
	"\agateway\x18\x03 \x01(\tR\agateway\x12-\n" +
	"\x12routing_configured\x18\x04 \x01(\bR\x11routingConfigured\"\x8a\x01\n" +
	"\x11DelNetworkRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\x12\x15\n" +
	"\x06vpc_ip\x18\x04 \x01(\tR\x05vpcIp\"Y\n" +
	"\x12DelNetworkResponse\x12\x1a\n" +
	"\breleased\x18\x01 \x01(\bR\breleased\x12'\n" +
	"\x0frouting_removed\x18\x02 \x01(\bR\x0eroutingRemoved\"w\n" +
	"\x15GetNetworkInfoRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x19\n" +
	"\bpod_name\x18\x02 \x01(\tR\apodName\x12%\n" +
	"\x0econtainer_name\x18\x03 \x01(\tR\rcontainerName\"\x84\x01\n" +
	"\x16GetNetworkInfoResponse\x12\x15\n" +
	"\x06vpc_ip\x18\x01 \x01(\tR\x05vpcIp\x12$\n" +
	"\x0evm_internal_ip\x18\x02 \x01(\tR\fvmInternalIp\x12-\n" +
	"\x12routing_configured\x18\x03 \x01(\bR\x11routingConfigured2\xd5\x01\n" +
	"\n" +
	"CNIService\x12=\n" +
	"\n" +
	"AddNetwork\x12\x16.cni.AddNetworkRequest\x1a\x17.cni.AddNetworkResponse\x12=\n" +
	"\n" +
	"DelNetwork\x12\x16.cni.DelNetworkRequest\x1a\x17.cni.DelNetworkResponse\x12I\n" +
	"\x0eGetNetworkInfo\x12\x1a.cni.GetNetworkInfoRequest\x1a\x1b.cni.GetNetworkInfoResponseB5Z3github.com/agoda-com/macOS-vz-kubelet/pkg/cni/protob\x06proto3"

var (
	file_pkg_cni_proto_cni_proto_rawDescOnce sync.Once
	file_pkg_cni_proto_cni_proto_rawDescData []byte
)

func file_pkg_cni_proto_cni_proto_rawDescGZIP() []byte {
	file_pkg_cni_proto_cni_proto_rawDescOnce.Do(func() {
		file_pkg_cni_proto_cni_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_cni_proto_cni_proto_rawDesc), len(file_pkg_cni_proto_cni_proto_rawDesc)))
	})
	return file_pkg_cni_proto_cni_proto_rawDescData
}

var file_pkg_cni_proto_cni_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_cni_proto_cni_proto_goTypes = []any{
	(*AddNetworkRequest)(nil),      // 0: cni.AddNetworkRequest
	(*AddNetworkResponse)(nil),     // 1: cni.AddNetworkResponse
	(*DelNetworkRequest)(nil),      // 2: cni.DelNetworkRequest
	(*DelNetworkResponse)(nil),     // 3: cni.DelNetworkResponse
	(*GetNetworkInfoRequest)(nil),  // 4: cni.GetNetworkInfoRequest
	(*GetNetworkInfoResponse)(nil), // 5: cni.GetNetworkInfoResponse
}
var file_pkg_cni_proto_cni_proto_depIdxs = []int32{
	0, // 0: cni.CNIService.AddNetwork:input_type -> cni.AddNetworkRequest
	2, // 1: cni.CNIService.DelNetwork:input_type -> cni.DelNetworkRequest
	4, // 2: cni.CNIService.GetNetworkInfo:input_type -> cni.GetNetworkInfoRequest
	1, // 3: cni.CNIService.AddNetwork:output_type -> cni.AddNetworkResponse
	3, // 4: cni.CNIService.DelNetwork:output_type -> cni.DelNetworkResponse
	5, // 5: cni.CNIService.GetNetworkInfo:output_type -> cni.GetNetworkInfoResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_cni_proto_cni_proto_init() }
func file_pkg_cni_proto_cni_proto_init() {
	if File_pkg_cni_proto_cni_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_cni_proto_cni_proto_rawDesc), len(file_pkg_cni_proto_cni_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_cni_proto_cni_proto_goTypes,
		DependencyIndexes: file_pkg_cni_proto_cni_proto_depIdxs,
		MessageInfos:      file_pkg_cni_proto_cni_proto_msgTypes,
	}.Build()
	File_pkg_cni_proto_cni_proto = out.File
	file_pkg_cni_proto_cni_proto_goTypes = nil
	file_pkg_cni_proto_cni_proto_depIdxs = nil
}
