// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: pkg/cni/proto/cni.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CNIService_AddNetwork_FullMethodName     = "/cni.CNIService/AddNetwork"
	CNIService_DelNetwork_FullMethodName     = "/cni.CNIService/DelNetwork"
	CNIService_GetNetworkInfo_FullMethodName = "/cni.CNIService/GetNetworkInfo"
)

// CNIServiceClient is the client API for CNIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// CNIService manages VPC networking for macOS VMs.
// It assigns secondary VPC IPs to VMs and configures routing/NAT.
type CNIServiceClient interface {
	// AddNetwork assigns a VPC IP to a VM and configures routing.
	// Called when a new VM pod is created.
	AddNetwork(ctx context.Context, in *AddNetworkRequest, opts ...grpc.CallOption) (*AddNetworkResponse, error)
	// DelNetwork releases a VPC IP and removes routing configuration.
	// Called when a VM pod is deleted.
	DelNetwork(ctx context.Context, in *DelNetworkRequest, opts ...grpc.CallOption) (*DelNetworkResponse, error)
	// GetNetworkInfo returns the current network configuration for a VM.
	GetNetworkInfo(ctx context.Context, in *GetNetworkInfoRequest, opts ...grpc.CallOption) (*GetNetworkInfoResponse, error)
}

type cNIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCNIServiceClient(cc grpc.ClientConnInterface) CNIServiceClient {
	return &cNIServiceClient{cc}
}

func (c *cNIServiceClient) AddNetwork(ctx context.Context, in *AddNetworkRequest, opts ...grpc.CallOption) (*AddNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddNetworkResponse)
	err := c.cc.Invoke(ctx, CNIService_AddNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIServiceClient) DelNetwork(ctx context.Context, in *DelNetworkRequest, opts ...grpc.CallOption) (*DelNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DelNetworkResponse)
	err := c.cc.Invoke(ctx, CNIService_DelNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cNIServiceClient) GetNetworkInfo(ctx context.Context, in *GetNetworkInfoRequest, opts ...grpc.CallOption) (*GetNetworkInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkInfoResponse)
	err := c.cc.Invoke(ctx, CNIService_GetNetworkInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CNIServiceServer is the server API for CNIService service.
// All implementations must embed UnimplementedCNIServiceServer
// for forward compatibility.
//
// CNIService manages VPC networking for macOS VMs.
// It assigns secondary VPC IPs to VMs and configures routing/NAT.
type CNIServiceServer interface {
	// AddNetwork assigns a VPC IP to a VM and configures routing.
	// Called when a new VM pod is created.
	AddNetwork(context.Context, *AddNetworkRequest) (*AddNetworkResponse, error)
	// DelNetwork releases a VPC IP and removes routing configuration.
	// Called when a VM pod is deleted.
	DelNetwork(context.Context, *DelNetworkRequest) (*DelNetworkResponse, error)
	// GetNetworkInfo returns the current network configuration for a VM.
	GetNetworkInfo(context.Context, *GetNetworkInfoRequest) (*GetNetworkInfoResponse, error)
	mustEmbedUnimplementedCNIServiceServer()
}

// UnimplementedCNIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCNIServiceServer struct{}

func (UnimplementedCNIServiceServer) AddNetwork(context.Context, *AddNetworkRequest) (*AddNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNetwork not implemented")
}
func (UnimplementedCNIServiceServer) DelNetwork(context.Context, *DelNetworkRequest) (*DelNetworkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DelNetwork not implemented")
}
func (UnimplementedCNIServiceServer) GetNetworkInfo(context.Context, *GetNetworkInfoRequest) (*GetNetworkInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNetworkInfo not implemented")
}
func (UnimplementedCNIServiceServer) mustEmbedUnimplementedCNIServiceServer() {}
func (UnimplementedCNIServiceServer) testEmbeddedByValue()                    {}

// UnsafeCNIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CNIServiceServer will
// result in compilation errors.
type UnsafeCNIServiceServer interface {
	mustEmbedUnimplementedCNIServiceServer()
}

func RegisterCNIServiceServer(s grpc.ServiceRegistrar, srv CNIServiceServer) {
	// If the following call panics, it indicates UnimplementedCNIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CNIService_ServiceDesc, srv)
}

func _CNIService_AddNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIServiceServer).AddNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNIService_AddNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIServiceServer).AddNetwork(ctx, req.(*AddNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNIService_DelNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIServiceServer).DelNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNIService_DelNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIServiceServer).DelNetwork(ctx, req.(*DelNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CNIService_GetNetworkInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CNIServiceServer).GetNetworkInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CNIService_GetNetworkInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CNIServiceServer).GetNetworkInfo(ctx, req.(*GetNetworkInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CNIService_ServiceDesc is the grpc.ServiceDesc for CNIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CNIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cni.CNIService",
	HandlerType: (*CNIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddNetwork",
			Handler:    _CNIService_AddNetwork_Handler,
		},
		{
			MethodName: "DelNetwork",
			Handler:    _CNIService_DelNetwork_Handler,
		},
		{
			MethodName: "GetNetworkInfo",
			Handler:    _CNIService_GetNetworkInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/cni/proto/cni.proto",
}
