// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewEventRecorder creates a new instance of EventRecorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventRecorder {
	mock := &EventRecorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// EventRecorder is an autogenerated mock type for the EventRecorder type
type EventRecorder struct {
	mock.Mock
}

type EventRecorder_Expecter struct {
	mock *mock.Mock
}

func (_m *EventRecorder) EXPECT() *EventRecorder_Expecter {
	return &EventRecorder_Expecter{mock: &_m.Mock}
}

// BackOffPullImage provides a mock function for the type EventRecorder
func (_mock *EventRecorder) BackOffPullImage(ctx context.Context, image string, containerName string, err error) {
	_mock.Called(ctx, image, containerName, err)
	return
}

// EventRecorder_BackOffPullImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BackOffPullImage'
type EventRecorder_BackOffPullImage_Call struct {
	*mock.Call
}

// BackOffPullImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
//   - containerName string
//   - err error
func (_e *EventRecorder_Expecter) BackOffPullImage(ctx interface{}, image interface{}, containerName interface{}, err interface{}) *EventRecorder_BackOffPullImage_Call {
	return &EventRecorder_BackOffPullImage_Call{Call: _e.mock.On("BackOffPullImage", ctx, image, containerName, err)}
}

func (_c *EventRecorder_BackOffPullImage_Call) Run(run func(ctx context.Context, image string, containerName string, err error)) *EventRecorder_BackOffPullImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 error
		if args[3] != nil {
			arg3 = args[3].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EventRecorder_BackOffPullImage_Call) Return() *EventRecorder_BackOffPullImage_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_BackOffPullImage_Call) RunAndReturn(run func(ctx context.Context, image string, containerName string, err error)) *EventRecorder_BackOffPullImage_Call {
	_c.Run(run)
	return _c
}

// CreatedContainer provides a mock function for the type EventRecorder
func (_mock *EventRecorder) CreatedContainer(ctx context.Context, containerName string) {
	_mock.Called(ctx, containerName)
	return
}

// EventRecorder_CreatedContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreatedContainer'
type EventRecorder_CreatedContainer_Call struct {
	*mock.Call
}

// CreatedContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
func (_e *EventRecorder_Expecter) CreatedContainer(ctx interface{}, containerName interface{}) *EventRecorder_CreatedContainer_Call {
	return &EventRecorder_CreatedContainer_Call{Call: _e.mock.On("CreatedContainer", ctx, containerName)}
}

func (_c *EventRecorder_CreatedContainer_Call) Run(run func(ctx context.Context, containerName string)) *EventRecorder_CreatedContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EventRecorder_CreatedContainer_Call) Return() *EventRecorder_CreatedContainer_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_CreatedContainer_Call) RunAndReturn(run func(ctx context.Context, containerName string)) *EventRecorder_CreatedContainer_Call {
	_c.Run(run)
	return _c
}

// FailedPostStartHook provides a mock function for the type EventRecorder
func (_mock *EventRecorder) FailedPostStartHook(ctx context.Context, containerName string, cmd []string, err error) {
	_mock.Called(ctx, containerName, cmd, err)
	return
}

// EventRecorder_FailedPostStartHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedPostStartHook'
type EventRecorder_FailedPostStartHook_Call struct {
	*mock.Call
}

// FailedPostStartHook is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - cmd []string
//   - err error
func (_e *EventRecorder_Expecter) FailedPostStartHook(ctx interface{}, containerName interface{}, cmd interface{}, err interface{}) *EventRecorder_FailedPostStartHook_Call {
	return &EventRecorder_FailedPostStartHook_Call{Call: _e.mock.On("FailedPostStartHook", ctx, containerName, cmd, err)}
}

func (_c *EventRecorder_FailedPostStartHook_Call) Run(run func(ctx context.Context, containerName string, cmd []string, err error)) *EventRecorder_FailedPostStartHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 error
		if args[3] != nil {
			arg3 = args[3].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EventRecorder_FailedPostStartHook_Call) Return() *EventRecorder_FailedPostStartHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_FailedPostStartHook_Call) RunAndReturn(run func(ctx context.Context, containerName string, cmd []string, err error)) *EventRecorder_FailedPostStartHook_Call {
	_c.Run(run)
	return _c
}

// FailedPreStopHook provides a mock function for the type EventRecorder
func (_mock *EventRecorder) FailedPreStopHook(ctx context.Context, containerName string, cmd []string, err error) {
	_mock.Called(ctx, containerName, cmd, err)
	return
}

// EventRecorder_FailedPreStopHook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedPreStopHook'
type EventRecorder_FailedPreStopHook_Call struct {
	*mock.Call
}

// FailedPreStopHook is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - cmd []string
//   - err error
func (_e *EventRecorder_Expecter) FailedPreStopHook(ctx interface{}, containerName interface{}, cmd interface{}, err interface{}) *EventRecorder_FailedPreStopHook_Call {
	return &EventRecorder_FailedPreStopHook_Call{Call: _e.mock.On("FailedPreStopHook", ctx, containerName, cmd, err)}
}

func (_c *EventRecorder_FailedPreStopHook_Call) Run(run func(ctx context.Context, containerName string, cmd []string, err error)) *EventRecorder_FailedPreStopHook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 error
		if args[3] != nil {
			arg3 = args[3].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EventRecorder_FailedPreStopHook_Call) Return() *EventRecorder_FailedPreStopHook_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_FailedPreStopHook_Call) RunAndReturn(run func(ctx context.Context, containerName string, cmd []string, err error)) *EventRecorder_FailedPreStopHook_Call {
	_c.Run(run)
	return _c
}

// FailedToCreateContainer provides a mock function for the type EventRecorder
func (_mock *EventRecorder) FailedToCreateContainer(ctx context.Context, containerName string, err error) {
	_mock.Called(ctx, containerName, err)
	return
}

// EventRecorder_FailedToCreateContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedToCreateContainer'
type EventRecorder_FailedToCreateContainer_Call struct {
	*mock.Call
}

// FailedToCreateContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - err error
func (_e *EventRecorder_Expecter) FailedToCreateContainer(ctx interface{}, containerName interface{}, err interface{}) *EventRecorder_FailedToCreateContainer_Call {
	return &EventRecorder_FailedToCreateContainer_Call{Call: _e.mock.On("FailedToCreateContainer", ctx, containerName, err)}
}

func (_c *EventRecorder_FailedToCreateContainer_Call) Run(run func(ctx context.Context, containerName string, err error)) *EventRecorder_FailedToCreateContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EventRecorder_FailedToCreateContainer_Call) Return() *EventRecorder_FailedToCreateContainer_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_FailedToCreateContainer_Call) RunAndReturn(run func(ctx context.Context, containerName string, err error)) *EventRecorder_FailedToCreateContainer_Call {
	_c.Run(run)
	return _c
}

// FailedToPullImage provides a mock function for the type EventRecorder
func (_mock *EventRecorder) FailedToPullImage(ctx context.Context, image string, containerName string, err error) {
	_mock.Called(ctx, image, containerName, err)
	return
}

// EventRecorder_FailedToPullImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedToPullImage'
type EventRecorder_FailedToPullImage_Call struct {
	*mock.Call
}

// FailedToPullImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
//   - containerName string
//   - err error
func (_e *EventRecorder_Expecter) FailedToPullImage(ctx interface{}, image interface{}, containerName interface{}, err interface{}) *EventRecorder_FailedToPullImage_Call {
	return &EventRecorder_FailedToPullImage_Call{Call: _e.mock.On("FailedToPullImage", ctx, image, containerName, err)}
}

func (_c *EventRecorder_FailedToPullImage_Call) Run(run func(ctx context.Context, image string, containerName string, err error)) *EventRecorder_FailedToPullImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 error
		if args[3] != nil {
			arg3 = args[3].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EventRecorder_FailedToPullImage_Call) Return() *EventRecorder_FailedToPullImage_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_FailedToPullImage_Call) RunAndReturn(run func(ctx context.Context, image string, containerName string, err error)) *EventRecorder_FailedToPullImage_Call {
	_c.Run(run)
	return _c
}

// FailedToResolveImagePullSecrets provides a mock function for the type EventRecorder
func (_mock *EventRecorder) FailedToResolveImagePullSecrets(ctx context.Context, err error) {
	_mock.Called(ctx, err)
	return
}

// EventRecorder_FailedToResolveImagePullSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedToResolveImagePullSecrets'
type EventRecorder_FailedToResolveImagePullSecrets_Call struct {
	*mock.Call
}

// FailedToResolveImagePullSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - err error
func (_e *EventRecorder_Expecter) FailedToResolveImagePullSecrets(ctx interface{}, err interface{}) *EventRecorder_FailedToResolveImagePullSecrets_Call {
	return &EventRecorder_FailedToResolveImagePullSecrets_Call{Call: _e.mock.On("FailedToResolveImagePullSecrets", ctx, err)}
}

func (_c *EventRecorder_FailedToResolveImagePullSecrets_Call) Run(run func(ctx context.Context, err error)) *EventRecorder_FailedToResolveImagePullSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 error
		if args[1] != nil {
			arg1 = args[1].(error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EventRecorder_FailedToResolveImagePullSecrets_Call) Return() *EventRecorder_FailedToResolveImagePullSecrets_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_FailedToResolveImagePullSecrets_Call) RunAndReturn(run func(ctx context.Context, err error)) *EventRecorder_FailedToResolveImagePullSecrets_Call {
	_c.Run(run)
	return _c
}

// FailedToStartContainer provides a mock function for the type EventRecorder
func (_mock *EventRecorder) FailedToStartContainer(ctx context.Context, containerName string, err error) {
	_mock.Called(ctx, containerName, err)
	return
}

// EventRecorder_FailedToStartContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedToStartContainer'
type EventRecorder_FailedToStartContainer_Call struct {
	*mock.Call
}

// FailedToStartContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
//   - err error
func (_e *EventRecorder_Expecter) FailedToStartContainer(ctx interface{}, containerName interface{}, err interface{}) *EventRecorder_FailedToStartContainer_Call {
	return &EventRecorder_FailedToStartContainer_Call{Call: _e.mock.On("FailedToStartContainer", ctx, containerName, err)}
}

func (_c *EventRecorder_FailedToStartContainer_Call) Run(run func(ctx context.Context, containerName string, err error)) *EventRecorder_FailedToStartContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EventRecorder_FailedToStartContainer_Call) Return() *EventRecorder_FailedToStartContainer_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_FailedToStartContainer_Call) RunAndReturn(run func(ctx context.Context, containerName string, err error)) *EventRecorder_FailedToStartContainer_Call {
	_c.Run(run)
	return _c
}

// FailedToValidateOCI provides a mock function for the type EventRecorder
func (_mock *EventRecorder) FailedToValidateOCI(ctx context.Context, content string) {
	_mock.Called(ctx, content)
	return
}

// EventRecorder_FailedToValidateOCI_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FailedToValidateOCI'
type EventRecorder_FailedToValidateOCI_Call struct {
	*mock.Call
}

// FailedToValidateOCI is a helper method to define mock.On call
//   - ctx context.Context
//   - content string
func (_e *EventRecorder_Expecter) FailedToValidateOCI(ctx interface{}, content interface{}) *EventRecorder_FailedToValidateOCI_Call {
	return &EventRecorder_FailedToValidateOCI_Call{Call: _e.mock.On("FailedToValidateOCI", ctx, content)}
}

func (_c *EventRecorder_FailedToValidateOCI_Call) Run(run func(ctx context.Context, content string)) *EventRecorder_FailedToValidateOCI_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EventRecorder_FailedToValidateOCI_Call) Return() *EventRecorder_FailedToValidateOCI_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_FailedToValidateOCI_Call) RunAndReturn(run func(ctx context.Context, content string)) *EventRecorder_FailedToValidateOCI_Call {
	_c.Run(run)
	return _c
}

// PulledImage provides a mock function for the type EventRecorder
func (_mock *EventRecorder) PulledImage(ctx context.Context, image string, containerName string, duration string) {
	_mock.Called(ctx, image, containerName, duration)
	return
}

// EventRecorder_PulledImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PulledImage'
type EventRecorder_PulledImage_Call struct {
	*mock.Call
}

// PulledImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
//   - containerName string
//   - duration string
func (_e *EventRecorder_Expecter) PulledImage(ctx interface{}, image interface{}, containerName interface{}, duration interface{}) *EventRecorder_PulledImage_Call {
	return &EventRecorder_PulledImage_Call{Call: _e.mock.On("PulledImage", ctx, image, containerName, duration)}
}

func (_c *EventRecorder_PulledImage_Call) Run(run func(ctx context.Context, image string, containerName string, duration string)) *EventRecorder_PulledImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *EventRecorder_PulledImage_Call) Return() *EventRecorder_PulledImage_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_PulledImage_Call) RunAndReturn(run func(ctx context.Context, image string, containerName string, duration string)) *EventRecorder_PulledImage_Call {
	_c.Run(run)
	return _c
}

// PullingImage provides a mock function for the type EventRecorder
func (_mock *EventRecorder) PullingImage(ctx context.Context, image string, containerName string) {
	_mock.Called(ctx, image, containerName)
	return
}

// EventRecorder_PullingImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PullingImage'
type EventRecorder_PullingImage_Call struct {
	*mock.Call
}

// PullingImage is a helper method to define mock.On call
//   - ctx context.Context
//   - image string
//   - containerName string
func (_e *EventRecorder_Expecter) PullingImage(ctx interface{}, image interface{}, containerName interface{}) *EventRecorder_PullingImage_Call {
	return &EventRecorder_PullingImage_Call{Call: _e.mock.On("PullingImage", ctx, image, containerName)}
}

func (_c *EventRecorder_PullingImage_Call) Run(run func(ctx context.Context, image string, containerName string)) *EventRecorder_PullingImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *EventRecorder_PullingImage_Call) Return() *EventRecorder_PullingImage_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_PullingImage_Call) RunAndReturn(run func(ctx context.Context, image string, containerName string)) *EventRecorder_PullingImage_Call {
	_c.Run(run)
	return _c
}

// StartedContainer provides a mock function for the type EventRecorder
func (_mock *EventRecorder) StartedContainer(ctx context.Context, containerName string) {
	_mock.Called(ctx, containerName)
	return
}

// EventRecorder_StartedContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartedContainer'
type EventRecorder_StartedContainer_Call struct {
	*mock.Call
}

// StartedContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - containerName string
func (_e *EventRecorder_Expecter) StartedContainer(ctx interface{}, containerName interface{}) *EventRecorder_StartedContainer_Call {
	return &EventRecorder_StartedContainer_Call{Call: _e.mock.On("StartedContainer", ctx, containerName)}
}

func (_c *EventRecorder_StartedContainer_Call) Run(run func(ctx context.Context, containerName string)) *EventRecorder_StartedContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *EventRecorder_StartedContainer_Call) Return() *EventRecorder_StartedContainer_Call {
	_c.Call.Return()
	return _c
}

func (_c *EventRecorder_StartedContainer_Call) RunAndReturn(run func(ctx context.Context, containerName string)) *EventRecorder_StartedContainer_Call {
	_c.Run(run)
	return _c
}
