// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/agoda-com/macOS-vz-kubelet/pkg/client"
	"github.com/agoda-com/macOS-vz-kubelet/pkg/resource"
	mock "github.com/stretchr/testify/mock"
	"github.com/virtual-kubelet/virtual-kubelet/node/api"
	"k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
	"k8s.io/kubelet/pkg/apis/stats/v1alpha1"
)

// NewVzClientInterface creates a new instance of VzClientInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVzClientInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *VzClientInterface {
	mock := &VzClientInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VzClientInterface is an autogenerated mock type for the VzClientInterface type
type VzClientInterface struct {
	mock.Mock
}

type VzClientInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *VzClientInterface) EXPECT() *VzClientInterface_Expecter {
	return &VzClientInterface_Expecter{mock: &_m.Mock}
}

// AttachToContainer provides a mock function for the type VzClientInterface
func (_mock *VzClientInterface) AttachToContainer(ctx context.Context, namespace string, podName string, containerName string, attach api.AttachIO) error {
	ret := _mock.Called(ctx, namespace, podName, containerName, attach)

	if len(ret) == 0 {
		panic("no return value specified for AttachToContainer")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, api.AttachIO) error); ok {
		r0 = returnFunc(ctx, namespace, podName, containerName, attach)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VzClientInterface_AttachToContainer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AttachToContainer'
type VzClientInterface_AttachToContainer_Call struct {
	*mock.Call
}

// AttachToContainer is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - podName string
//   - containerName string
//   - attach api.AttachIO
func (_e *VzClientInterface_Expecter) AttachToContainer(ctx interface{}, namespace interface{}, podName interface{}, containerName interface{}, attach interface{}) *VzClientInterface_AttachToContainer_Call {
	return &VzClientInterface_AttachToContainer_Call{Call: _e.mock.On("AttachToContainer", ctx, namespace, podName, containerName, attach)}
}

func (_c *VzClientInterface_AttachToContainer_Call) Run(run func(ctx context.Context, namespace string, podName string, containerName string, attach api.AttachIO)) *VzClientInterface_AttachToContainer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 api.AttachIO
		if args[4] != nil {
			arg4 = args[4].(api.AttachIO)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *VzClientInterface_AttachToContainer_Call) Return(err error) *VzClientInterface_AttachToContainer_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VzClientInterface_AttachToContainer_Call) RunAndReturn(run func(ctx context.Context, namespace string, podName string, containerName string, attach api.AttachIO) error) *VzClientInterface_AttachToContainer_Call {
	_c.Call.Return(run)
	return _c
}

// CreateVirtualizationGroup provides a mock function for the type VzClientInterface
func (_mock *VzClientInterface) CreateVirtualizationGroup(ctx context.Context, pod *v1.Pod, serviceAccountToken string, configMaps map[string]*v1.ConfigMap, creds resource.RegistryCredentialStore) error {
	ret := _mock.Called(ctx, pod, serviceAccountToken, configMaps, creds)

	if len(ret) == 0 {
		panic("no return value specified for CreateVirtualizationGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *v1.Pod, string, map[string]*v1.ConfigMap, resource.RegistryCredentialStore) error); ok {
		r0 = returnFunc(ctx, pod, serviceAccountToken, configMaps, creds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VzClientInterface_CreateVirtualizationGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateVirtualizationGroup'
type VzClientInterface_CreateVirtualizationGroup_Call struct {
	*mock.Call
}

// CreateVirtualizationGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - pod *v1.Pod
//   - serviceAccountToken string
//   - configMaps map[string]*v1.ConfigMap
//   - creds resource.RegistryCredentialStore
func (_e *VzClientInterface_Expecter) CreateVirtualizationGroup(ctx interface{}, pod interface{}, serviceAccountToken interface{}, configMaps interface{}, creds interface{}) *VzClientInterface_CreateVirtualizationGroup_Call {
	return &VzClientInterface_CreateVirtualizationGroup_Call{Call: _e.mock.On("CreateVirtualizationGroup", ctx, pod, serviceAccountToken, configMaps, creds)}
}

func (_c *VzClientInterface_CreateVirtualizationGroup_Call) Run(run func(ctx context.Context, pod *v1.Pod, serviceAccountToken string, configMaps map[string]*v1.ConfigMap, creds resource.RegistryCredentialStore)) *VzClientInterface_CreateVirtualizationGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *v1.Pod
		if args[1] != nil {
			arg1 = args[1].(*v1.Pod)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 map[string]*v1.ConfigMap
		if args[3] != nil {
			arg3 = args[3].(map[string]*v1.ConfigMap)
		}
		var arg4 resource.RegistryCredentialStore
		if args[4] != nil {
			arg4 = args[4].(resource.RegistryCredentialStore)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *VzClientInterface_CreateVirtualizationGroup_Call) Return(err error) *VzClientInterface_CreateVirtualizationGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VzClientInterface_CreateVirtualizationGroup_Call) RunAndReturn(run func(ctx context.Context, pod *v1.Pod, serviceAccountToken string, configMaps map[string]*v1.ConfigMap, creds resource.RegistryCredentialStore) error) *VzClientInterface_CreateVirtualizationGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteVirtualizationGroup provides a mock function for the type VzClientInterface
func (_mock *VzClientInterface) DeleteVirtualizationGroup(ctx context.Context, namespace string, name string, gracePeriod int64) error {
	ret := _mock.Called(ctx, namespace, name, gracePeriod)

	if len(ret) == 0 {
		panic("no return value specified for DeleteVirtualizationGroup")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = returnFunc(ctx, namespace, name, gracePeriod)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VzClientInterface_DeleteVirtualizationGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteVirtualizationGroup'
type VzClientInterface_DeleteVirtualizationGroup_Call struct {
	*mock.Call
}

// DeleteVirtualizationGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
//   - gracePeriod int64
func (_e *VzClientInterface_Expecter) DeleteVirtualizationGroup(ctx interface{}, namespace interface{}, name interface{}, gracePeriod interface{}) *VzClientInterface_DeleteVirtualizationGroup_Call {
	return &VzClientInterface_DeleteVirtualizationGroup_Call{Call: _e.mock.On("DeleteVirtualizationGroup", ctx, namespace, name, gracePeriod)}
}

func (_c *VzClientInterface_DeleteVirtualizationGroup_Call) Run(run func(ctx context.Context, namespace string, name string, gracePeriod int64)) *VzClientInterface_DeleteVirtualizationGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *VzClientInterface_DeleteVirtualizationGroup_Call) Return(err error) *VzClientInterface_DeleteVirtualizationGroup_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VzClientInterface_DeleteVirtualizationGroup_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string, gracePeriod int64) error) *VzClientInterface_DeleteVirtualizationGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ExecuteContainerCommand provides a mock function for the type VzClientInterface
func (_mock *VzClientInterface) ExecuteContainerCommand(ctx context.Context, namespace string, podName string, containerName string, cmd []string, attach api.AttachIO) error {
	ret := _mock.Called(ctx, namespace, podName, containerName, cmd, attach)

	if len(ret) == 0 {
		panic("no return value specified for ExecuteContainerCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, []string, api.AttachIO) error); ok {
		r0 = returnFunc(ctx, namespace, podName, containerName, cmd, attach)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VzClientInterface_ExecuteContainerCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExecuteContainerCommand'
type VzClientInterface_ExecuteContainerCommand_Call struct {
	*mock.Call
}

// ExecuteContainerCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - podName string
//   - containerName string
//   - cmd []string
//   - attach api.AttachIO
func (_e *VzClientInterface_Expecter) ExecuteContainerCommand(ctx interface{}, namespace interface{}, podName interface{}, containerName interface{}, cmd interface{}, attach interface{}) *VzClientInterface_ExecuteContainerCommand_Call {
	return &VzClientInterface_ExecuteContainerCommand_Call{Call: _e.mock.On("ExecuteContainerCommand", ctx, namespace, podName, containerName, cmd, attach)}
}

func (_c *VzClientInterface_ExecuteContainerCommand_Call) Run(run func(ctx context.Context, namespace string, podName string, containerName string, cmd []string, attach api.AttachIO)) *VzClientInterface_ExecuteContainerCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 []string
		if args[4] != nil {
			arg4 = args[4].([]string)
		}
		var arg5 api.AttachIO
		if args[5] != nil {
			arg5 = args[5].(api.AttachIO)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *VzClientInterface_ExecuteContainerCommand_Call) Return(err error) *VzClientInterface_ExecuteContainerCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VzClientInterface_ExecuteContainerCommand_Call) RunAndReturn(run func(ctx context.Context, namespace string, podName string, containerName string, cmd []string, attach api.AttachIO) error) *VzClientInterface_ExecuteContainerCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetContainerLogs provides a mock function for the type VzClientInterface
func (_mock *VzClientInterface) GetContainerLogs(ctx context.Context, namespace string, podName string, containerName string, opts api.ContainerLogOpts) (io.ReadCloser, error) {
	ret := _mock.Called(ctx, namespace, podName, containerName, opts)

	if len(ret) == 0 {
		panic("no return value specified for GetContainerLogs")
	}

	var r0 io.ReadCloser
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, api.ContainerLogOpts) (io.ReadCloser, error)); ok {
		return returnFunc(ctx, namespace, podName, containerName, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, api.ContainerLogOpts) io.ReadCloser); ok {
		r0 = returnFunc(ctx, namespace, podName, containerName, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, api.ContainerLogOpts) error); ok {
		r1 = returnFunc(ctx, namespace, podName, containerName, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VzClientInterface_GetContainerLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetContainerLogs'
type VzClientInterface_GetContainerLogs_Call struct {
	*mock.Call
}

// GetContainerLogs is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - podName string
//   - containerName string
//   - opts api.ContainerLogOpts
func (_e *VzClientInterface_Expecter) GetContainerLogs(ctx interface{}, namespace interface{}, podName interface{}, containerName interface{}, opts interface{}) *VzClientInterface_GetContainerLogs_Call {
	return &VzClientInterface_GetContainerLogs_Call{Call: _e.mock.On("GetContainerLogs", ctx, namespace, podName, containerName, opts)}
}

func (_c *VzClientInterface_GetContainerLogs_Call) Run(run func(ctx context.Context, namespace string, podName string, containerName string, opts api.ContainerLogOpts)) *VzClientInterface_GetContainerLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 api.ContainerLogOpts
		if args[4] != nil {
			arg4 = args[4].(api.ContainerLogOpts)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *VzClientInterface_GetContainerLogs_Call) Return(readCloser io.ReadCloser, err error) *VzClientInterface_GetContainerLogs_Call {
	_c.Call.Return(readCloser, err)
	return _c
}

func (_c *VzClientInterface_GetContainerLogs_Call) RunAndReturn(run func(ctx context.Context, namespace string, podName string, containerName string, opts api.ContainerLogOpts) (io.ReadCloser, error)) *VzClientInterface_GetContainerLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetVirtualizationGroup provides a mock function for the type VzClientInterface
func (_mock *VzClientInterface) GetVirtualizationGroup(ctx context.Context, namespace string, name string) (*client.VirtualizationGroup, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetVirtualizationGroup")
	}

	var r0 *client.VirtualizationGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*client.VirtualizationGroup, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *client.VirtualizationGroup); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.VirtualizationGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VzClientInterface_GetVirtualizationGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVirtualizationGroup'
type VzClientInterface_GetVirtualizationGroup_Call struct {
	*mock.Call
}

// GetVirtualizationGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *VzClientInterface_Expecter) GetVirtualizationGroup(ctx interface{}, namespace interface{}, name interface{}) *VzClientInterface_GetVirtualizationGroup_Call {
	return &VzClientInterface_GetVirtualizationGroup_Call{Call: _e.mock.On("GetVirtualizationGroup", ctx, namespace, name)}
}

func (_c *VzClientInterface_GetVirtualizationGroup_Call) Run(run func(ctx context.Context, namespace string, name string)) *VzClientInterface_GetVirtualizationGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *VzClientInterface_GetVirtualizationGroup_Call) Return(virtualizationGroup *client.VirtualizationGroup, err error) *VzClientInterface_GetVirtualizationGroup_Call {
	_c.Call.Return(virtualizationGroup, err)
	return _c
}

func (_c *VzClientInterface_GetVirtualizationGroup_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*client.VirtualizationGroup, error)) *VzClientInterface_GetVirtualizationGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetVirtualizationGroupListResult provides a mock function for the type VzClientInterface
func (_mock *VzClientInterface) GetVirtualizationGroupListResult(ctx context.Context) (map[types.NamespacedName]*client.VirtualizationGroup, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetVirtualizationGroupListResult")
	}

	var r0 map[types.NamespacedName]*client.VirtualizationGroup
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[types.NamespacedName]*client.VirtualizationGroup, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[types.NamespacedName]*client.VirtualizationGroup); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[types.NamespacedName]*client.VirtualizationGroup)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VzClientInterface_GetVirtualizationGroupListResult_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVirtualizationGroupListResult'
type VzClientInterface_GetVirtualizationGroupListResult_Call struct {
	*mock.Call
}

// GetVirtualizationGroupListResult is a helper method to define mock.On call
//   - ctx context.Context
func (_e *VzClientInterface_Expecter) GetVirtualizationGroupListResult(ctx interface{}) *VzClientInterface_GetVirtualizationGroupListResult_Call {
	return &VzClientInterface_GetVirtualizationGroupListResult_Call{Call: _e.mock.On("GetVirtualizationGroupListResult", ctx)}
}

func (_c *VzClientInterface_GetVirtualizationGroupListResult_Call) Run(run func(ctx context.Context)) *VzClientInterface_GetVirtualizationGroupListResult_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VzClientInterface_GetVirtualizationGroupListResult_Call) Return(namespacedNameToVirtualizationGroup map[types.NamespacedName]*client.VirtualizationGroup, err error) *VzClientInterface_GetVirtualizationGroupListResult_Call {
	_c.Call.Return(namespacedNameToVirtualizationGroup, err)
	return _c
}

func (_c *VzClientInterface_GetVirtualizationGroupListResult_Call) RunAndReturn(run func(ctx context.Context) (map[types.NamespacedName]*client.VirtualizationGroup, error)) *VzClientInterface_GetVirtualizationGroupListResult_Call {
	_c.Call.Return(run)
	return _c
}

// GetVirtualizationGroupStats provides a mock function for the type VzClientInterface
func (_mock *VzClientInterface) GetVirtualizationGroupStats(ctx context.Context, namespace string, name string, containers []v1.Container) ([]v1alpha1.ContainerStats, error) {
	ret := _mock.Called(ctx, namespace, name, containers)

	if len(ret) == 0 {
		panic("no return value specified for GetVirtualizationGroupStats")
	}

	var r0 []v1alpha1.ContainerStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []v1.Container) ([]v1alpha1.ContainerStats, error)); ok {
		return returnFunc(ctx, namespace, name, containers)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []v1.Container) []v1alpha1.ContainerStats); ok {
		r0 = returnFunc(ctx, namespace, name, containers)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1alpha1.ContainerStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, []v1.Container) error); ok {
		r1 = returnFunc(ctx, namespace, name, containers)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// VzClientInterface_GetVirtualizationGroupStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVirtualizationGroupStats'
type VzClientInterface_GetVirtualizationGroupStats_Call struct {
	*mock.Call
}

// GetVirtualizationGroupStats is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
//   - containers []v1.Container
func (_e *VzClientInterface_Expecter) GetVirtualizationGroupStats(ctx interface{}, namespace interface{}, name interface{}, containers interface{}) *VzClientInterface_GetVirtualizationGroupStats_Call {
	return &VzClientInterface_GetVirtualizationGroupStats_Call{Call: _e.mock.On("GetVirtualizationGroupStats", ctx, namespace, name, containers)}
}

func (_c *VzClientInterface_GetVirtualizationGroupStats_Call) Run(run func(ctx context.Context, namespace string, name string, containers []v1.Container)) *VzClientInterface_GetVirtualizationGroupStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []v1.Container
		if args[3] != nil {
			arg3 = args[3].([]v1.Container)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *VzClientInterface_GetVirtualizationGroupStats_Call) Return(containerStatss []v1alpha1.ContainerStats, err error) *VzClientInterface_GetVirtualizationGroupStats_Call {
	_c.Call.Return(containerStatss, err)
	return _c
}

func (_c *VzClientInterface_GetVirtualizationGroupStats_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string, containers []v1.Container) ([]v1alpha1.ContainerStats, error)) *VzClientInterface_GetVirtualizationGroupStats_Call {
	_c.Call.Return(run)
	return _c
}
