// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	"github.com/agoda-com/macOS-vz-kubelet/pkg/resource"
	mock "github.com/stretchr/testify/mock"
	"k8s.io/api/core/v1"
)

// NewVirtualMachine creates a new instance of VirtualMachine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVirtualMachine(t interface {
	mock.TestingT
	Cleanup(func())
}) *VirtualMachine {
	mock := &VirtualMachine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// VirtualMachine is an autogenerated mock type for the VirtualMachine type
type VirtualMachine struct {
	mock.Mock
}

type VirtualMachine_Expecter struct {
	mock *mock.Mock
}

func (_m *VirtualMachine) EXPECT() *VirtualMachine_Expecter {
	return &VirtualMachine_Expecter{mock: &_m.Mock}
}

// Env provides a mock function for the type VirtualMachine
func (_mock *VirtualMachine) Env() []v1.EnvVar {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Env")
	}

	var r0 []v1.EnvVar
	if returnFunc, ok := ret.Get(0).(func() []v1.EnvVar); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]v1.EnvVar)
		}
	}
	return r0
}

// VirtualMachine_Env_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Env'
type VirtualMachine_Env_Call struct {
	*mock.Call
}

// Env is a helper method to define mock.On call
func (_e *VirtualMachine_Expecter) Env() *VirtualMachine_Env_Call {
	return &VirtualMachine_Env_Call{Call: _e.mock.On("Env")}
}

func (_c *VirtualMachine_Env_Call) Run(run func()) *VirtualMachine_Env_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VirtualMachine_Env_Call) Return(envVars []v1.EnvVar) *VirtualMachine_Env_Call {
	_c.Call.Return(envVars)
	return _c
}

func (_c *VirtualMachine_Env_Call) RunAndReturn(run func() []v1.EnvVar) *VirtualMachine_Env_Call {
	_c.Call.Return(run)
	return _c
}

// Error provides a mock function for the type VirtualMachine
func (_mock *VirtualMachine) Error() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Error")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// VirtualMachine_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type VirtualMachine_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
func (_e *VirtualMachine_Expecter) Error() *VirtualMachine_Error_Call {
	return &VirtualMachine_Error_Call{Call: _e.mock.On("Error")}
}

func (_c *VirtualMachine_Error_Call) Run(run func()) *VirtualMachine_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VirtualMachine_Error_Call) Return(err error) *VirtualMachine_Error_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *VirtualMachine_Error_Call) RunAndReturn(run func() error) *VirtualMachine_Error_Call {
	_c.Call.Return(run)
	return _c
}

// FinishedAt provides a mock function for the type VirtualMachine
func (_mock *VirtualMachine) FinishedAt() *time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for FinishedAt")
	}

	var r0 *time.Time
	if returnFunc, ok := ret.Get(0).(func() *time.Time); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}
	return r0
}

// VirtualMachine_FinishedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FinishedAt'
type VirtualMachine_FinishedAt_Call struct {
	*mock.Call
}

// FinishedAt is a helper method to define mock.On call
func (_e *VirtualMachine_Expecter) FinishedAt() *VirtualMachine_FinishedAt_Call {
	return &VirtualMachine_FinishedAt_Call{Call: _e.mock.On("FinishedAt")}
}

func (_c *VirtualMachine_FinishedAt_Call) Run(run func()) *VirtualMachine_FinishedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VirtualMachine_FinishedAt_Call) Return(time1 *time.Time) *VirtualMachine_FinishedAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *VirtualMachine_FinishedAt_Call) RunAndReturn(run func() *time.Time) *VirtualMachine_FinishedAt_Call {
	_c.Call.Return(run)
	return _c
}

// IPAddress provides a mock function for the type VirtualMachine
func (_mock *VirtualMachine) IPAddress() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IPAddress")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// VirtualMachine_IPAddress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IPAddress'
type VirtualMachine_IPAddress_Call struct {
	*mock.Call
}

// IPAddress is a helper method to define mock.On call
func (_e *VirtualMachine_Expecter) IPAddress() *VirtualMachine_IPAddress_Call {
	return &VirtualMachine_IPAddress_Call{Call: _e.mock.On("IPAddress")}
}

func (_c *VirtualMachine_IPAddress_Call) Run(run func()) *VirtualMachine_IPAddress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VirtualMachine_IPAddress_Call) Return(s string) *VirtualMachine_IPAddress_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *VirtualMachine_IPAddress_Call) RunAndReturn(run func() string) *VirtualMachine_IPAddress_Call {
	_c.Call.Return(run)
	return _c
}

// SetError provides a mock function for the type VirtualMachine
func (_mock *VirtualMachine) SetError(err error) {
	_mock.Called(err)
	return
}

// VirtualMachine_SetError_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetError'
type VirtualMachine_SetError_Call struct {
	*mock.Call
}

// SetError is a helper method to define mock.On call
//   - err error
func (_e *VirtualMachine_Expecter) SetError(err interface{}) *VirtualMachine_SetError_Call {
	return &VirtualMachine_SetError_Call{Call: _e.mock.On("SetError", err)}
}

func (_c *VirtualMachine_SetError_Call) Run(run func(err error)) *VirtualMachine_SetError_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *VirtualMachine_SetError_Call) Return() *VirtualMachine_SetError_Call {
	_c.Call.Return()
	return _c
}

func (_c *VirtualMachine_SetError_Call) RunAndReturn(run func(err error)) *VirtualMachine_SetError_Call {
	_c.Run(run)
	return _c
}

// StartedAt provides a mock function for the type VirtualMachine
func (_mock *VirtualMachine) StartedAt() *time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for StartedAt")
	}

	var r0 *time.Time
	if returnFunc, ok := ret.Get(0).(func() *time.Time); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*time.Time)
		}
	}
	return r0
}

// VirtualMachine_StartedAt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartedAt'
type VirtualMachine_StartedAt_Call struct {
	*mock.Call
}

// StartedAt is a helper method to define mock.On call
func (_e *VirtualMachine_Expecter) StartedAt() *VirtualMachine_StartedAt_Call {
	return &VirtualMachine_StartedAt_Call{Call: _e.mock.On("StartedAt")}
}

func (_c *VirtualMachine_StartedAt_Call) Run(run func()) *VirtualMachine_StartedAt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VirtualMachine_StartedAt_Call) Return(time1 *time.Time) *VirtualMachine_StartedAt_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *VirtualMachine_StartedAt_Call) RunAndReturn(run func() *time.Time) *VirtualMachine_StartedAt_Call {
	_c.Call.Return(run)
	return _c
}

// State provides a mock function for the type VirtualMachine
func (_mock *VirtualMachine) State() resource.VirtualMachineState {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for State")
	}

	var r0 resource.VirtualMachineState
	if returnFunc, ok := ret.Get(0).(func() resource.VirtualMachineState); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(resource.VirtualMachineState)
	}
	return r0
}

// VirtualMachine_State_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'State'
type VirtualMachine_State_Call struct {
	*mock.Call
}

// State is a helper method to define mock.On call
func (_e *VirtualMachine_Expecter) State() *VirtualMachine_State_Call {
	return &VirtualMachine_State_Call{Call: _e.mock.On("State")}
}

func (_c *VirtualMachine_State_Call) Run(run func()) *VirtualMachine_State_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *VirtualMachine_State_Call) Return(virtualMachineState resource.VirtualMachineState) *VirtualMachine_State_Call {
	_c.Call.Return(virtualMachineState)
	return _c
}

func (_c *VirtualMachine_State_Call) RunAndReturn(run func() resource.VirtualMachineState) *VirtualMachine_State_Call {
	_c.Call.Return(run)
	return _c
}
